import { AnalysisResult } from '../lib/schemas';
import { TestRun } from '../models/testRun';

export class TicketService {

    static generateMarkdownTicket(testRun: any, analysis: AnalysisResult): string {
        const title = `[TestAgent] ${analysis.root_cause}: ${analysis.reasoning.substring(0, 50)}...`;

        return `
# 🚨 ${title}

**Severity:** ${analysis.severity}
**Root Cause:** ${analysis.root_cause}

## 📝 Description
The agent failed a black-box audit during the "${testRun.scenario}" scenario.

## 🔍 Failure Analysis
**What went wrong:**
${analysis.reasoning}

**Evidence (Violation Quote):**
> "${analysis.violation_quote}"

## 🛠 Recommended Fix
${analysis.recommendation}

---
*Generated by TestAgent Auto-Triage*
`;
    }
}
